name: deploy EcommApp
on:
  push:
    branches: [ "main" ]   # change to "master" if your branch is master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup jdk 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with maven
        run: mvn -B package --file pom.xml
      - name: deploy to tomcat
        run: curl -v -u admin:admin -T /home/runner/work/Ecomm-project/Ecomm-project/target/Ecomm.war 'http://13.235.9.56:8080/manager/text/deploy?path=/Ecomm.war'

